/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplojframe;

import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class Ejemplo extends javax.swing.JFrame {

    /**
     * Creates new form Ejemplo
     */
    public Ejemplo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbTituloVentana = new javax.swing.JLabel();
        lbNombres = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        lbCorreo = new javax.swing.JLabel();
        lbCarrera = new javax.swing.JLabel();
        lbCiclo = new javax.swing.JLabel();
        tfNombres = new javax.swing.JTextField();
        tbApellidos = new javax.swing.JTextField();
        tfCorreo = new javax.swing.JTextField();
        btRegistrar = new javax.swing.JButton();
        rbCiclo01 = new javax.swing.JRadioButton();
        rbCiclo02 = new javax.swing.JRadioButton();
        cbCarrera = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTituloVentana.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        lbTituloVentana.setText("DATOS DEL ALUMNO");

        lbNombres.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbNombres.setText("Nombres:");

        lbApellidos.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbApellidos.setText("Apellidos");

        lbCorreo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbCorreo.setText("Correo:");

        lbCarrera.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbCarrera.setText("Carrera:");

        lbCiclo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbCiclo.setText("Ciclo Actual");

        tfNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombresActionPerformed(evt);
            }
        });

        tbApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbApellidosActionPerformed(evt);
            }
        });

        btRegistrar.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        btRegistrar.setText("REGISTRAR");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCiclo01);
        rbCiclo01.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbCiclo01.setText("Ciclo 01");
        rbCiclo01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCiclo01ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCiclo02);
        rbCiclo02.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbCiclo02.setText("Ciclo 02");
        rbCiclo02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCiclo02ActionPerformed(evt);
            }
        });

        cbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Ing.Sistemas", "Ing.Electrica", "ing.Industrial", "Ing.Agronegocios" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 3, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbNombres)
                                        .addGap(213, 213, 213))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbApellidos)
                                        .addGap(216, 216, 216))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCorreo)
                                    .addComponent(lbCarrera)
                                    .addComponent(lbCiclo))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rbCiclo01, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                            .addComponent(rbCiclo02))
                                        .addComponent(tfCorreo)
                                        .addComponent(cbCarrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tbApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lbTituloVentana))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btRegistrar)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbTituloVentana)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombres)
                    .addComponent(tfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbApellidos)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tbApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCorreo))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCarrera)
                    .addComponent(cbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCiclo)
                    .addComponent(rbCiclo01)
                    .addComponent(rbCiclo02))
                .addGap(18, 18, 18)
                .addComponent(btRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbApellidosActionPerformed

    private void tfNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombresActionPerformed

    private void rbCiclo01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCiclo01ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbCiclo01ActionPerformed

    private void rbCiclo02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCiclo02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCiclo02ActionPerformed

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
            // TODO add your handling code here
        String cicloActual = "";
        String carrera = "";
        String camposDeTexto = "";
        
        String carreraSeleccionada = (String) this.cbCarrera.getSelectedItem();
        
         // Validación de campos vacíos
        if (this.tfNombres.getText().isEmpty() || this.tfNombres.getText().isEmpty()
            || this.tfCorreo.getText().isEmpty()) {
            camposDeTexto = "-1";
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Sale del método si algún campo está vacío
        }
        
        //Validacion opcion por defecto
        if("Seleccione una opción".equals(carreraSeleccionada)){
            carrera = "-1";
            JOptionPane.showMessageDialog(this,"Seleccione una carrera.","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        //Validación del ciclo
        if(this.rbCiclo01.isSelected()){
            cicloActual = "01";
        }else if(this.rbCiclo02.isSelected()){
            cicloActual = "02";
        }else{
            cicloActual = "-1";
            JOptionPane.showMessageDialog(this,"Seleccione un ciclo.","Error",JOptionPane.ERROR_MESSAGE);
            //"Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        if(!"-1".equals(cicloActual) && !"-1".equals(carrera) && 
           !"-1".equals(camposDeTexto)){
        JOptionPane.showMessageDialog(this,"Registro exitoso de "
        +this.tfNombres.getText()+" "
        +this.tfNombres.getText()
        +" estudiante de la carrera de "
        +this.cbCarrera.getSelectedItem()
        +" con el correo "
        +this.tfCorreo.getText()
        +" en el Ciclo "+cicloActual);
        }
        

    }//GEN-LAST:event_btRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejemplo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCarrera;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbCarrera;
    private javax.swing.JLabel lbCiclo;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbTituloVentana;
    private javax.swing.JRadioButton rbCiclo01;
    private javax.swing.JRadioButton rbCiclo02;
    private javax.swing.JTextField tbApellidos;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfNombres;
    // End of variables declaration//GEN-END:variables
}
